
services:
  nginx_app:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: 
      - 443:443
    volumes:
      - type: bind
        source: /home/kyolee/data
        target: /data
    networks:
      - my_network
    restart: always
  wordpress_app:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
       - "9000"
    volumes:
      - type: bind
        source: /home/kyolee/data
        target: /data
    networks:
      - my_network
    depends_on:
      - db_app
      - nginx_app
    restart: always
  db_app:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    env_file:
      - .env
    tty: true
    expose:
       - "3306"
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - my_network
    restart: always
  ftp:
    build:
      context: ./requirements/bonus/ftp/
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "21"
      - "20"
    networks:
      - my_network
    restart: always
  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    expose:
      - "9001"
    networks:
      - my_network
    restart: always
  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "6379"  #for redis server
      - "9100"  #for node exporter
    networks:
      - my_network
    restart: always
  prometheus:
    build:
      context: ./requirements/bonus/prometheus
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "9090"
    networks:
      - my_network
    volumes:
      - prometheus_volume:/data
volumes:
  db_volume:
  prometheus_volume:
networks:
  my_network:
