version: "3.7"

services:
  nginx_app:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    env_file:
      - nginx.env
    ports: 
      - 443:443
    volumes:
      - ./requirements/nginx/conf/my.conf:/etc/nginx/http.d/my.conf
      - wordpress_volume:/data
    networks:
      - my_network
  wordpress_app:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    expose:
       - "9000"
    volumes:
      - ./requirements/wordpress/conf/www.conf:/etc/php8/php-fpm.d/www.conf
      - wordpress_volume:/data
    networks:
      - my_network
    depends_on:
      - db_app
      - nginx_app
    tty: true
    
  db_app:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    tty: true
    expose:
       - "3306"
    volumes:
      - db_volume:/var/lib/mysql
      - ./requirements/mariadb/conf/my.cnf:/etc/mysql/my.cnf
    networks:
      - my_network

volumes:
  wordpress_volume:
  db_volume:
networks:
  my_network:

